# Generated by Django 3.0.6 on 2020-10-30 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201026_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_title', models.CharField(max_length=200)),
                ('subcategory_image', models.ImageField(upload_to='')),
                ('subcategory_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
    ]
