# Generated by Django 3.0.6 on 2020-11-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
    ]
