# Generated by Django 3.0.6 on 2020-11-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_category_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_image',
        ),
    ]
